apiVersion: v1
kind: Service
metadata:
  name: springbootapp-service
spec:
  type: ClusterIP #LoadBalancer or NodePort – To receive external traffic ClusterIP –  If Nginx  run*,Traffic in
  selector:
    app: mongo
  ports:
  - port: 80
    targetPort: 8080
